### ISSUE TITLE
Recommend update of documentation

### ISSUE THREAD

**Issue by kimfucious** [ndom91/react-timezone-select#10]
Very cool product!  Thank you for sharing.

One small nit regarding the docs.

Unless I've overlooked something, using `selectedTimezone` in the below, will not show the selected value:
```js
<TimezoneSelect
   value={selectedTimezone}
    onChange={tz => setSelectedTimezone(tz)}
/>
```
What's needed here is to add `value` or some other key from the selectedTimezone object, like so:
```js
<TimezoneSelect
  value={selectedTimezone.value ? selectedTimezone.value : ""}
  onChange={(tz) => setSelectedTimezone(tz)}
/>
```
While it might seem obvious on how to show that value, the docs are slightly misleading as written and may confuse new users.

Again, nice product! 🌮

**Comment by ndom91** [comment]
@kimfucious first of all, thanks for the feedback!

I wasn't sure myself, so I double checked the code, but the component takes the value key of the object you pass in to the `value` prop itself already, so theres no need from the user side to do this. You can pass in the whole object.

I have adjusted it in the most recent commit though to also work if someone passes in just the value itself, not the whole object, so that its a bit more forgiving - sorry if the docs were misleading!

**Comment by kimfucious** [comment]
Thanks, @ndom91,

At present with v0.9.3, the value does not display, if I just use selectedTimezone.

I do need to use `value` or someting else to have the selection show in the select component after onChange().

**Comment by ndom91** [comment]
@kimfucious okay gotcha. I just double checked everything and pushed a new version - `0.9.6`. Should be good to pass `value.value`, so to speak, or the whole object you get back from `onChange` now. I didn't want to break anyone using one way while still fixing this.

**Comment by kimfucious** [comment]
HI @ndom91,

Thanks for the reply and quick action.

To clarify, I'm storing the entire `tz` object in state, so if I set the `value` and/or `defaultValue` props of the `TimezoneSelect` component, it appears that I need to use `value` and `label` respectively for those props, in order for them to display; otherwise, I just get the placeholder.
```jsx
<TimezoneSelect
  styles={customStyles}
  classNamePrefix="timezone-select"
  isDisabled={isUpdatingTimezone}
  isClearable={true}
  labelStyle="original"
  defaultInputValue={
    friend.notificationTimezone &&
    friend.notificationTimezone.label
      ? friend.notificationTimezone.label
      : ""
  }
  value={
    friend.notificationTimezone &&
    friend.notificationTimezone.value
      ? friend.notificationTimezone.value
      : ""
  }
  onChange={(tz) => handleTimezoneSelect(tz)}
/>
```
For the record, `friend.notificationTimezone` is `handleTimezoneSelect(tx)` is storing the `tz` object.

Things are working as expected in the above, but if you see that I'm doing something wrong, kindly let me know.

**Comment by ndom91** [comment]
Yeah so `react-select` - the select component this is based upon - requires a `value` value of an object with _atleast_ two keys, `label` and `value`, i.e. `{ value: '', label: '' }`. You can add other stuff, like we do here with `abbrev` and `altName`. 

In regards to your use of the component, looks good to me, I can't say much about the `defaultInputValue`, but I know the `value` value can now simply be `friend.notificationTimezone`, therefore, you could simplify it to:

```jsx
<TimezoneSelect
  styles={customStyles}
  classNamePrefix="timezone-select"
  isDisabled={isUpdatingTimezone}
  isClearable={true}
  labelStyle="original"
  defaultInputValue={
    friend.notificationTimezone &&
    friend.notificationTimezone.label
      ? friend.notificationTimezone.label
      : ""
  }
  value={
    friend.notificationTimezone 
      ? friend.notificationTimezone
      : ""
  }
  onChange={(tz) => handleTimezoneSelect(tz)}
/>
```

Or if you set the default state value for `notificationTimezone` as an empty string, then

```jsx
<TimezoneSelect
  styles={customStyles}
  classNamePrefix="timezone-select"
  isDisabled={isUpdatingTimezone}
  isClearable={true}
  labelStyle="original"
  defaultInputValue={
    friend.notificationTimezone &&
    friend.notificationTimezone.label
      ? friend.notificationTimezone.label
      : ""
  }
  value={friend.notificationTimezone}
  onChange={(tz) => handleTimezoneSelect(tz)}
/>
```

**Comment by kimfucious** [comment]
Hi @ndom91,

Thanks for the reply.

I've not upgraded to the latest, but I'll do that soon and report back.

As it stands, things are working as expected with v0.9.3.

Regarding `defaultInputValue`, as far as I understand it, if the user is returning to the screen where the selector exists, it needs this prop to display something prior to the the user actually selecting somthing.

The `friend.notificationTimezone` in the above is provided via a React `useSelector` hook, which is pulling from state.

Without this prop, the component will only show the placeholder when using only the `value` prop.
