### ISSUE TITLE
More options for how the timezone name is rendered (e.g. removing the offset)

### ISSUE THREAD

**Issue by lee-tms** [ndom91/react-timezone-select#106]
### Clear and concise description of the problem

We'd like the option to not show the offset. As we're allowing users to select a timezone and that offset may change due to daylight savings movements between when they select the time and when it applies, we feel the offset may confuse the user so would like to hide it.

That isn't currently an option.

### Suggested solution

I thought the label labelStyle prop would give me that option but it only amends a small part of that string.

Allowing a prop that dictates which of the values to use (value, label, abrrev or altName) instead of a default would probably get it done.

A 'show offset' boolean flag would be another option.

Or a label prop that allows for a template string to be passed, e.g. 

`%altName% (%value%) - %offset%-GMT`

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
hey @lee-tms, sure that's not to difficult!

I've added it in `2.1.5` - let me know what you think!

See demo at: https://ndom91.github.io/react-timezone-select/

![image](https://github.com/ndom91/react-timezone-select/assets/7415984/421a1032-d159-4ca4-a12b-5d39365ca394)
