### ISSUE TITLE
Warning: Prop `id` did not match. Server: "react-select-2-live-region" Client: "react-select-3-live-region" error

### ISSUE THREAD

**Issue by DyloG783** [ndom91/react-timezone-select#108]
### Describe the bug

When using the example code from the github code example I get this error on every render and refresh. If I remove the 
`<TimezoneSelect
                    value={selectedTimezone}
                    onChange={() => setSelectedTimezone}
/>`

component the error goes away. The component isn't updating state when I select options from the dropdown.

I'm using latest react/next (latest of all packages as of today i.e. Next 14.0.0). 

(first time writing a post like this so apologies if I'm not expressing this better).

### Reproduction

Attempt to render component as per github code example

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
    Memory: 24.04 GB / 31.93 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.69)
    Internet Explorer: 11.0.19041.3570
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Linus-f** [comment]
I had the same issue in Next 13 with `react-select`. The issue seems to be related to Emotion, which apparently doesn't play nicely with Remix and Next.js. 

I found an issue with a solution for my problem ([react-select issue](https://github.com/JedWatson/react-select/issues/5459#issuecomment-1458451734)). Hope it helps you too.

**Comment by DyloG783** [comment]
Thanks for the response, I ended up going with the [timezones.json](https://www.npmjs.com/package/timezones.json) package and using my own basic select dropdown. It's a shame because I liked the styling of this component.
