### ISSUE TITLE
Select timezone by value name

### ISSUE THREAD

**Issue by ya-ya-it** [ndom91/react-timezone-select#11]
Hello! Thanks for the package!

I'm storing only the value from the JSON object in the database. How can I then match the value with a dropdown to preselect the correct timezone? 
So for example, I'm storing in the database "America/Detroit" but when I pass it to the value or the defaultInputValue it only shows me the string, not the timezone object.

Thanks!

**Comment by ndom91** [comment]
Hey so thanks for filing this. I adjusted how the `value` value is parsed and released an update (0.9.7) on npm just now where this should work.

Please give it a shot and let me know if that clears it up for you!

**Comment by ndom91** [comment]
If you don't have any other questions or concerns, I will close this issue in the coming days. Thanks!

**Comment by ya-ya-it** [comment]
Sorry for the late reply! Thank you very much for the quick fix! Everything is working perfectly now, I love it!
