### ISSUE TITLE
For fuzzy matching, the same continent adds 2 score

### ISSUE THREAD

**Issue by rzdong** [ndom91/react-timezone-select#115]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-timezone-select@3.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-timezone-select/dist/index.js b/node_modules/react-timezone-select/dist/index.js
index 470805e..378126d 100644
--- a/node_modules/react-timezone-select/dist/index.js
+++ b/node_modules/react-timezone-select/dist/index.js
@@ -188,7 +188,7 @@ function useTimezoneSelect({
         ) !== -1) {
           score += 4;
         }
-        if (tz.value.toLowerCase().indexOf(currentTime.tz.substring(0, currentTime.tz.indexOf("/")))) {
+        if (tz.value.toLowerCase().indexOf(currentTime.tz.substring(0, currentTime.tz.indexOf("/"))) !== -1) {
           score += 2;
         }
         score += 1;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ndom91** [comment]
Nice catch! Thanks for the patch example. This should be fixed in `v3.2.2` :pray:
