### ISSUE TITLE
Tijuana US and Canada is mapped to America/Dawson timezone

### ISSUE THREAD

**Issue by akilansengottaiyan** [ndom91/react-timezone-select#12]
Good day!
To my knowledge, `America/Dawson timezone(utc-7)` is different from the timezone in `Tijuana US and Canada(utc-8)`. 
But in the dropdown, typing either of them results in `America/Dawson`
In the code `i18n` object defined in `src/index.js` ,  `Tijuana, Pacific Time` is mapped to `America/Dawson` timezone which shouldn't be the case.
This is causing problem since there is no way to differentiate between them.
Wanted to bring to your notice if its a bug or the intention here. 
Feel free to correct me if I wrong.
Thanks

**Comment by ndom91** [comment]
@akilansengottaiyan thanks for the heads up! I just published a `v0.9.8` on npm which changed it to 'America/Tijuana'. 

Let me know if that clears it up for you!

**Comment by akilansengottaiyan** [comment]
@ndom91 Thanks for the fix. Now there is no way to add America/Dawson timezone now. Isn't it needed now to add one more entry for America/Dawson timezone in the dictionary? 
Let me know if I am wrong in intrepreting it.

**Comment by ndom91** [comment]
Technically your right, there's no `America/Dawson`, but there's a bunch of other GMT-7:00's. 

Do you need the Dawson choice specifically? I can add it back in for you.

**Comment by ndom91** [comment]
If theres nothing else to do here, I will close this issue this week. Thanks!

**Comment by akilansengottaiyan** [comment]
Hey @ndom91. I guess it would be better to add Dawson specifically. Thanks.

**Comment by ndom91** [comment]
Okay so I've changed the `Tijuana, Pacific Time` choice to `America/Tijuana` and added a Dawson choice at `America/Dawson` with the label `Dawson, Yukon` :+1: 

Is available in v0.9.12+
