### ISSUE TITLE
Cairo returns undefined label/abbreviation

### ISSUE THREAD

**Issue by ayuhito** [ndom91/react-timezone-select#125]
### Describe the bug

![image](https://github.com/ndom91/react-timezone-select/assets/38220115/0586f2d3-4a5d-4727-a8c7-8a8d25291a6b)

Appreciate this library a lot since it has saved me a quite a bit of time. Thank you!

### Reproduction

Can be reproduced in the official demo by selecting Cairo.

### System Info

```Shell
Firefox 126
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Thanks for pointing this out. We're using [timezone-soft](https://github.com/spencermountain/timezone-soft) library to get timezone info, and it looks like "Africa/Cairo" doesn't have a daylight savings time, which caused this to end up being `undefined`. I just shipped a little update to just not include the abbreviation suffix in cases like these though.

So long story short, shoudl be good to go in `v3.2.7` :pray:
