### ISSUE TITLE
parseTimezone throws runtime error when the zone is "Null"

### ISSUE THREAD

**Issue by salmanorak** [ndom91/react-timezone-select#127]
### Describe the bug

When somehow the zone value passed to the parseTimezone function is null it throws a runtime error from the below line. Since `typeof null` is `object`, it hits the zone.value => null.value and throws error.

```ts
    if (typeof zone === "object" && zone.value && zone.label) return zone
```

I could add an early return for null values but couldn't be sure about what I should return in this case from parseTimezone.

version: 3.2.5

### Reproduction

https://codesandbox.io/p/devbox/parsetimezone-null-error-5v5xy9

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 15.07 GB / 31.84 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\Volta\tools\image\node\20.11.0\node.EXE
    npm: 10.2.4 - ~\AppData\Local\Volta\tools\image\node\20.11.0\npm.CMD   
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
@salmanorak thanks for pointing this out. `null` isn't supposed to be passed as a `value` according to TS, but of course stuff happens, right.

So I just updated the parsing a bit and published `v3.2.6`. Let me know if that doesn't fix it for you :pray:
