### ISSUE TITLE
Can you set default values?

### ISSUE THREAD

**Issue by willydavid1** [ndom91/react-timezone-select#13]
hello I have a question and it is that I need to set a default value to the selector. Is it possible? example:
![image](https://user-images.githubusercontent.com/55035334/100788317-e99df200-33e2-11eb-8621-5a31fd47242d.png)

**Comment by ndom91** [comment]
Yes, it is possible. Are you using react hooks? i.e. `useState()` to save the current selection?

If so, you can define the default value was the default variable value whenever you declare the variable getter/setter.

For example:
```jsx
import React, { useEffect, useState } from "react"
import spacetime from "spacetime"
import TimezoneSelect from "react-timezone-select"
import "./styles.css"

export default function App() {
  const [tz, setTz] = useState("Europe/Berlin")
  const [datetime, setDatetime] = useState(spacetime.now())

  useEffect(() => {
    setDatetime(datetime.goto(tz.value))
  }, [tz, datetime])

  return (
    <div className="App">
      <h2>react-timezone-select + spacetime</h2>
      <div className="output">
        <div>
          datetime: <pre>{datetime.unixFmt("dd.MM.YY HH:mm:ss")}</pre>
        </div>
        <div>
          tz.value: <pre>{datetime.tz}</pre>
        </div>
      </div>
      <div className="timezone--wrapper">
        <TimezoneSelect style={{ width: "50px" }} value={tz} onChange={setTz} />
      </div>
    </div>
  )
}
```
Here I'm setting `Europe/Berlin` as the default selected timezone by defining it as the default value whenever I'm setting up the `tz` and `setTz` `useState` hook on line 6.

You can check out this [Codesandbox](https://codesandbox.io/s/react-timezone-select-usage-z37hf?file=/src/App.js) for a working example

**Comment by willydavid1** [comment]
It doesn't work for me at all because my goal was to have a label and time zone already set. what I did was the next thing that served me the same

**Comment by willydavid1** [comment]
It doesn't work for me at all because my goal was to have a label and time zone already set. what I did was the next thing that served me the same

```
const defaultTZValue = { abbrev: '', altName: '', label: '(GMT-5:00) Bogota, Lima, Quito', value: 'America/Bogota' }
const [selectedTimezone, setSelectedTimezone] = useState(() => {
    if (defaultTimeZone) {
      const prefix = `(GMT${defaultTimeZone?.['tz'] >= 0 ? `+${defaultTimeZone?.['tz']}` : `-${Math.abs(defaultTimeZone?.['tz'])}`}:00)`
      const timeZoneLabel = Object.entries(dataTimeZone).find((entry) => entry[0] === defaultTimeZone?.['nameTZ'])
      return {
        ...defaultTZValue,
        label: `${prefix} ${timeZoneLabel[1]}`,
        value: defaultTimeZone?.['nameTZ']
      }
    }
    return defaultTZValue
  })
```
**This is my default result:**
![image](https://user-images.githubusercontent.com/55035334/100896052-38539680-348c-11eb-8aa6-0a810941f2a7.png)

It would be great if someone passes a prop to their component as a default value, it is marked and has its corresponding label by default, as in my case.

**Comment by ndom91** [comment]
So I'm not sure what your whole useState callback is doing, but you can simplify your whole code into this one line basically:

```
const [selectedTimezone, setSelectedTimezone] = useState('America/Bogota')
```
