### ISSUE TITLE
Wrong timezone for 'Pacific/Fiji': 'Fiji Islands, Kamchatka, Marshall Islands',

### ISSUE THREAD

**Issue by RozumSystems** [ndom91/react-timezone-select#15]
Kamchatka should be GMT+12, but we have GTM+13 https://en.wikipedia.org/wiki/Kamchatka_Time

Pacific / Fiji looks like should be divided to 2 timezones, because Fiji has DST (GMT+12 / GMT +13), but Kamchatka don't
https://en.wikipedia.org/wiki/Time_in_Fiji

Marshal islands has +12 as in Kamchatka
https://en.wikipedia.org/wiki/Marshall_Islands

**Comment by ndom91** [comment]
Hi @RozumSystems, sorry its taken me so long to get to this!

So you're suggesting Marshall Islands should be bumped out into its own choice as it is the only one which does not follow DST? Am I understanding you correctly?

**Comment by RozumSystems** [comment]
Hi @ndom91, thanks for answer!

Probably it would be better to  divide  into 3 timezones?

Kamchatka (Russia)  GMT+12 and no DST
Fiji has DST 
Marshal Islands are right now as Kamchatka, but who know what will happen?

**Comment by ndom91** [comment]
Yeah okay, then how about this - i'll split Kamchatka and Marshall Islands into one and 
Fiji into another. 

We just released a new feature where you can define your own options / timezone choices, so if things change or you want to override further your free to do so 👍 

How does that sound?

**Comment by RozumSystems** [comment]
@ndom91, as for me - it fits perfectly.

Thanks a lot for your job!

**Comment by ndom91** [comment]
Okay great! I'll close this issue then. 

The change is in `main` and I've published a new version on npm with v0.9.14 :+1:
