### ISSUE TITLE
npm install error with React 17 dependency

### ISSUE THREAD

**Issue by chrishrtmn** [ndom91/react-timezone-select#18]
I get an error attempting to install this on React 17 - can you upgrade this to work with it? Thanks!

**Comment by ndom91** [comment]
Hi Chris,

Thanks for bringing this up! I moved react to a peerDependency and used this opportunity to version bump all other dependencies too. 

Try `react-timezone-select@0.9.10` from npm and let me know if you're still having issues!

**Comment by chrishrtmn** [comment]
Worked perfectly, thanks!

**Comment by ndom91** [comment]
Great, thanks for the quick feedback!

Ill close this issue then.

**Comment by stevokk** [comment]
@ndom91 when you bumped up the minimum version for React, was it for a breaking reason? I'm just wanting to use this in a React 16 project without having to do a v17 migration and thinking this is just a mistake in dependency requirements?

**Comment by ndom91** [comment]
> @ndom91 when you bumped up the minimum version for React, was it for a breaking reason? I'm just wanting to use this in a React 16 project without having to do a v17 migration and thinking this is just a mistake in dependency requirements?

Ah yes good call, didn't think it would disallow react 16 right away. Might be because of the npm7 peer deps thing. 

I'll double check the package.json and potentially publish a new version, but `npm install --legacy-peer-deps` should work as well 👍
