### ISSUE TITLE
How can I set a deffault Value?

### ISSUE THREAD

**Issue by gustavomm19** [ndom91/react-timezone-select#19]
Hi! I am trying to set a defaultValue by doing 
`defaultValue={entity && update? {timeZone:{label: entity.timeZone}} : {}}`
And I can see that the value object is changing but I don't see the value selected

**Comment by ndom91** [comment]
The best way to set a default value is to just set the variable which you are setting as `value` to something in the declaration in `useState`. 

See the useState line here for example:

```jsx
import React, { useState } from 'react'
import ReactDOM from 'react-dom'
import TimezoneSelect from 'react-timezone-select'

const App = () => {
  const [selectedTimezone, setSelectedTimezone] = useState("Europe/Amsterdam")

  return (
    <div className='App'>
      <h2>react-timezone-select</h2>
      <blockquote>Please make a selection</blockquote>
      <div className='select-wrapper'>
        <TimezoneSelect
          value={selectedTimezone}
          onChange={setSelectedTimezone}
        />
      </div>
    </div>
  )
}
```

**Comment by ndom91** [comment]
@gustavomm19 if you don't have any further questions I will close this issue this week. 

If you still have issues, feel free to reply or open another issue :+1:

**Comment by gustavomm19** [comment]
Thanks dude!
