### ISSUE TITLE
Menu Have and unwanted transparency with material components

### ISSUE THREAD

**Issue by gustavomm19** [ndom91/react-timezone-select#23]
Hi :)
I am making a form with material UI textfields. The problem is that when I display the list, the list have some kind of transparency and I can see the material textfields through the menu and it looks horrible. Here is a capture of what is going on:

![issue](https://user-images.githubusercontent.com/47191295/107464465-b7251980-6b36-11eb-8237-fe6485fff22f.png)

**Comment by ndom91** [comment]
Your right that does look awful, take a look at the z-index of the text of your input fields. 

Either that is higher than the z-index of the timezone dropdown or the timezone dropdown z-index is too low. I don't think it's a transparency (opacity) issue.

**Comment by gustavomm19** [comment]
You were right, it was a matter of the z-index, I fixed it by increasing the z-index of the menu.

**Comment by robozb** [comment]
> You were right, it was a matter of the z-index, I fixed it by increasing the z-index of the menu.

Dear @gustavomm19, 

How could you do that, increasing the zIndex of the TimezoneSelect (and its dropdown)? 

Thank you so much!

Bela

**Comment by robozb** [comment]
OK, I got it, both prop(menuPortalTarget and of course styles) is really important!!!

```
  <TimezoneSelect 
      ...
      menuPortalTarget={document.body} 
      styles={{ menuPortal: base => ({ ...base, zIndex: 9999 }) }}
      ...
  />
```
