### ISSUE TITLE
Feature request: Automatically detect user timeZone based on GMT offset

### ISSUE THREAD

**Issue by emrysal** [ndom91/react-timezone-select#25]
We've got a usecase where we want the use the dayjs.tz.guess() function, which for Italy for example may return Europe/Rome. This wouldn't resolve to anything in this case. 

Perhaps it is an idea to do some kind of map of GMT offset to timeZone?

**Comment by ndom91** [comment]
Hey thanks for bringing this up! 

So if I understand you correctly, you want to be able to pass in a GMT offset (i.e. `GMT+2:00`) and get back the full timezone object? [`spacetime`](https://github.com/spencermountain/spacetime#timezones) supports something similar, does that fulfill your usecase? If not, maybe [`moment-timezone`](https://momentjs.com/timezone/) does?

**Comment by ndom91** [comment]
Ah okay, so we can probably relatively easily select the default timezone via the users browser language / country headers or something like that.

Would that fulfill your use case?

**Comment by ndrwksr** [comment]
How's this?

```
const [timezone, setTimezone] = useState<ITimezone>(Intl.DateTimeFormat().resolvedOptions().timeZone);
  return <TimezoneSelect value={timezone} onChange={setTimezone}/>
```

I don't think this works in IE11 though.
https://caniuse.com/?search=DateTimeFormat

**Comment by ndom91** [comment]
Yeah just putting it as the default value in the useState call is what I would have done too. I didn't know the new `Intl` object had this though, thats awesome! 

Regarding IE11, thats okay I dont plan on going out of my way to support that anyway..

**Comment by ndom91** [comment]
Hey so I've released a new version last night with a bunch of clean up. 

Wasn't sure whether to put this into a prop the user could enable (i.e. `showUserTimezoneByDefault`) or something like that. 

But just decided to throw it in the readme for now since it makes more sense for the user to use your little `Intl` snippet in "userland" when they're initialising the state. 

Thanks again for the tip!

**Comment by ndrwksr** [comment]
@ndom91 You are very welcome. Thanks for making a wonderful open source component 😄

**Comment by ndom91** [comment]
Going to close this for now, if anyone comes across this looking for similar behavior - checkout @ndrwksr 's workaround in the comment above (https://github.com/ndom91/react-timezone-select/issues/25#issuecomment-827853301), or in the README.

**Comment by emrysal** [comment]
@ndom91 What I meant was what happens in the case the timezone is missing from the select. Attached a screenshot of what happens when the timeZone detected is Europe/Rome.

![image](https://user-images.githubusercontent.com/1046695/116422539-c06d7a80-a837-11eb-9577-9b7ad1673849.png)

**Comment by ndom91** [comment]
Ah gotcha. 

Yeah so there's two ways to deal with this. 

Either I expand the interior map to include every timezone in that "Europe/Rome" format. 

Or I make this "setUserTimezoneByDefault" thing an internal prop, and then I can match user timezones that don't exist (like Europe/Rome) by offset to the matching existing choice (Europe/Berlin or Europe/Amsterdam I think it'd be). 

What do you think? 

I'm up for #2

**Comment by emrysal** [comment]
The _Dumb approach_ I came up with is to indeed get a list together of all timezones in existance, and map them to the relevant "Short list". I think it is desireable from this component POV to deal with valid timezones that are not part of the component display (in case people want to do this). I was wondering if there were smarter ways like detecting an entered timezone GMT offset, and then find the item in the list with the same GMT offset rules. 

By logic, I think this belongs within the `parseTimezone` function (sidenote, this is typehinted ITimeZone but I think it's mixed at that point, either ITimezone or string, but alas). The way it can be handled is that when you pass "Europe/Rome" it returns an ITimeZone interface with Europe/Amsterdam, as that is the relevant match.

**Comment by ndrwksr** [comment]
@emrysal I believe this would be helpful:
https://github.com/spencermountain/timezone-soft/

**Comment by ndom91** [comment]
Btw @emrysal - regarding the union type `ITimezone`, this was done this way to support allowing people to just pass in "Europe/Amsterdam", for example, instead of the whole object. Mostly for backwards compatibility reasons. Maybe we should do a major version bump and just remove that..

**Comment by ndom91** [comment]
Hey everyone, @emrysal's PR to match any possible timezone to one in our list, has been merged! :tada:

This means you can safely use the `Intl.DateTimeFormat().resolvedOptions().timeZone` trick during state initialisation, and get a valid timezone selection out :+1:

**Comment by Mehdi-HAFID** [comment]
There is a problem with using `Intl.DateTimeFormat().resolvedOptions().timeZone` as a way to set the user timezone. say for example your timezone is Paris, Intl sets it as `Europe/Paris` and NOT `Europe/Brussels` which your library supports. now the selection works as you mentiend. Here is the Problem: I use your `import {allTimezones} from "react-timezone-select";` to display the timezone label `allTimezones[props.timeZone]` this evaluates to `undefined`. because you don't support all timezone so `Europe/Paris` is `undefined`. I'm considering using GMT as default Selection and always forcing the user to select the timezone himself, because I really like your `allTimezones` object.

**Comment by ndom91** [comment]
> There is a problem with using `Intl.DateTimeFormat().resolvedOptions().timeZone` as a way to set the user timezone. say for example your timezone is Paris, Intl sets it as `Europe/Paris` and NOT `Europe/Brussels` which your library supports. now the selection works as you mentiend. Here is the Problem: I use your `import {allTimezones} from "react-timezone-select";` to display the timezone label `allTimezones[props.timeZone]` this evaluates to `undefined`. because you don't support all timezone so `Europe/Paris` is `undefined`. I'm considering using GMT as default Selection and always forcing the user to select the timezone himself, because I really like your `allTimezones` object.

Yeah this is a known issue, someone has suggested auto detecting the city and generating the timezones dynamically in [this issue](https://github.com/ndom91/react-timezone-select/issues/71), but no movement yet.
