### ISSUE TITLE
Europe/London should be used rather than GMT to define British Timezones

### ISSUE THREAD

**Issue by jcoombs235** [ndom91/react-timezone-select#27]
Currently, Dublin, Edinburgh, Lisbon, London are all defined using the identifier GMT, this means that the component cannot adjust for British Summer Time (BST) and prevents the use of default values for this timezone as Europe/London is what is generated from Intl.DateTimeFormat().resolvedOptions().timeZone rather than GMT.

In my opinion, GMT should have the value of UTC, keeping GMT as the key. This way GMT can still be kept constant.

**Comment by ndom91** [comment]
I agree, good change! Thanks for the PR! :tada:
