### ISSUE TITLE
Asia/Baku offset

### ISSUE THREAD

**Issue by Irina-GO** [ndom91/react-timezone-select#33]
Which offset is right for Baku (GMT+5:00) Baku, Tbilisi, Yerevan or (GMT+4:00) ? where do you get this offset?
![Screenshot_2021-06-10_19-26-05](https://user-images.githubusercontent.com/77773826/121563365-03b82d00-ca23-11eb-976a-6ad2ebce79b4.png)
![Screenshot_2021-06-10_19-35-42](https://user-images.githubusercontent.com/77773826/121563402-0dda2b80-ca23-11eb-8fa1-75395866d56a.png)

**Comment by ndom91** [comment]
Update: our PR got merged into `spacetime` - so as soon as they release a new version we'll be good to go too! 

(If it takes a bit i'll just install it off their git master instead of npm, i'll keep an eye on it :+1:)

**Comment by ndom91** [comment]
`spacetime` released `6.16.2` and I just updated this library to `1.0.4` with this and other updated dependencies :tada:
