### ISSUE TITLE
Mouse cursor is set to "cursor: default"

### ISSUE THREAD

**Issue by UltraTempest** [ndom91/react-timezone-select#35]
Should the styling for the dropdown be changed from 
```css
cursor: default
```

to

```css
cursor: pointer
```

to better display the intent to the end user that this is an interactive element & also from an accessibility perspective?

**Comment by ndom91** [comment]
Hi @UltraTempest yeah probably. In theory I agree with you. 

However, we're using the [`react-select`](https://react-select.com/home) component as the underlying dropdown / select and they explicitly decided against it actually, but with the caveat that it was a breaking change and users could easily implement it themselves. (See: https://github.com/JedWatson/react-select/pull/4069)

Material-UI seems to have `cursor: pointer` on their selects, so I think its a safe / "correct" way to go about it (https://next.material-ui.com/components/selects/). 

I'll have a look at this later this evening :+1:

**Comment by UltraTempest** [comment]
Thanks @ndom91 Did you have a chance to take a look yet?

**Comment by ndom91** [comment]
Hey sorry, I had not. Seeing as material-ui defaults to `cursor: pointer` on their select fields, I think its an appropriate way to go. I'll see if I can whip up a PR for this tonight :+1:

**Comment by ndom91** [comment]
@UltraTempest so I did some digging and whipped up a PR with my own basic css import, check out `1.0.6` :tada:

**Comment by UltraTempest** [comment]
Legend thanks! :)
