### ISSUE TITLE
No updates in npm packages

### ISSUE THREAD

**Issue by otasman** [ndom91/react-timezone-select#37]
The source code for releases are not being updated in https://www.npmjs.com/package/react-timezone-select. The revision number gets updated but the files are staying the same.

**Comment by ndom91** [comment]
Yeah so the most recent update was just one to add an `index.css` file, otherwise nothing changed. But you are right in that the `index.css` file did not seem to be included! Thanks for that!

I've just released a `1.0.7` release where I can confirm that css file is included.

**Comment by otasman** [comment]
Awesome, thanks! I see the changes now
