### ISSUE TITLE
Component no longer accepting onChange handler?

### ISSUE THREAD

**Issue by dkulp23** [ndom91/react-timezone-select#4]
Hey Nico,

First off, thanks for taking the time to put this package together. I needed a simple timezone select for a project and this has worked perfectly.

However, just this morning I was doing a dependency audit on my project and noticed that the upgrade from `0.5.1` => `0.6.0` broke the functionality of the component.

If I'm reading [the source](https://github.com/ndom91/react-timezone-select/blob/master/src/index.js#L199) correctly, when you recently refactored to use hooks and a functional component, you are no longer using the `onChange` prop being passed in when the component is rendered? I was confused because this change is not reflected in the example. 

I see that you are passing through the `onBlur` prop but this did not work for my implementation.

Just off the top of my head I think it could be possible to create a new callback function inside `TimezoneSelect` which both calls the `props.onChange` function passed to the component and also calls the local `setSelectedTimezone` function. Then you could pass that wrapper as the callback to the `Select` `onChange`?

Many thanks again.
Cheers,
Dana

**Comment by dkulp23** [comment]
@ndom91 Works perfectly now! Thank you very much for the lightning fast response and update!

**Comment by ndom91** [comment]
Great to hear. No problem!
