### ISSUE TITLE
CSS import error when component is used with Next.js

### ISSUE THREAD

**Issue by trentprynn** [ndom91/react-timezone-select#41]
When attempting to use this component on a project built using Next.js I'm currently getting the following error

- `Global CSS cannot be imported from within node_modules`

The error links to [this Next.js documentation](https://nextjs.org/docs/messages/css-npm) page

I'm pretty sure this is because this component is doing `import "./index.css"` [here](https://github.com/ndom91/react-timezone-select/blob/main/src/index.tsx)

[Here is a stackblitz](https://stackblitz.com/edit/nextjs-wjpmra?file=pages/index.js) (must be run using chrome) that demonstrates the problem

**Comment by trentprynn** [comment]
I think any of the following options would resolve this issue and allow this component to be use in a Next.js project

1. Remove [this css file](https://github.com/ndom91/react-timezone-select/blob/main/src/index.css) and any references to it
    - could move the styles inline, or just remove them all together as its whole point is to give the `cursor: pointer`class which is something I don't think really matters (my opinion)
2. Compile the css into the js file during release? (don't know much about doing this)

**Comment by ndom91** [comment]
Hey @jartek, looks like Next.js is working on allowing this type of css import (of not css modules): https://github.com/vercel/next.js/discussions/27953
