### ISSUE TITLE
Error: Module parse failed: Unexpected token (22:59)

### ISSUE THREAD

**Issue by BananaGarden** [ndom91/react-timezone-select#47]
Issue when i run cmd: npm start

ERROR in ./node_modules/react-timezone-select/dist/index.js 22:59
Module parse failed: Unexpected token (22:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

The version used:
- "react-timezone-select": "^1.0.5",
- "react": "^17.0.2",

Webpack config:
`{
          test: /\.(js|jsx)$/,
          exclude: [
            {
              test: path.resolve(__dirname, 'node_modules'),
            },
          ],
          use: {
            loader: 'babel-loader',
          },
        },`

Has anyone had such a situation and solution?
Thanks!

**Comment by ndom91** [comment]
Hey @BananaGarden unfortunately I haven't been this error before. Are you using next.js or gatsby or any framework like that? 

I also noticed you're using a bit of an older version of this package. Maybe an upgrade to the latest `1.1.13` will fix it up for you :+1:

**Comment by ndom91** [comment]
@BananaGarden are you still having this issue? If I dont hear back from you i'll assume its been fixed and close this issue soon as its gone stale :+1:
