### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by mdilshan** [ndom91/react-timezone-select#48]
I have recently updated all the packages of my React project. With the updated project it is failed to compile due to the following error.

```
./node_modules/react-timezone-select/dist/index.js 31:53
Module parse failed: Unexpected token (31:53)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       let label = ""; // @ts-expect-error
| 
>       let abbr = now.isDST() ? tzStrings[0].daylight?.abbr : tzStrings[0].standard?.abbr;
|       let altName = now.isDST() ? tzStrings[0].daylight?.name : tzStrings[0].standard?.name;
|       const min = tz.current.offset * 60;

```
![image](https://user-images.githubusercontent.com/47513639/142130911-c02499fc-311d-40ce-8307-63c4936fc337.png)

Node JS Version - v14.17.3
React Version - 17.0.2
Typescript Version - 4.4.4

Project was created with `create-react-app`

**Comment by ndom91** [comment]
@mdilshan can you give the latest `v1.1.15` a shot? I just published it a few minutes ago. I couldn't reproduce your issue in a codesandbox.

If you're still having this issue with the latest version, a reproduction would be super helpful for me to help you further! 

Thanks.

**Comment by mdilshan** [comment]
@ndom91 It is working right now. Nice job :)
