### ISSUE TITLE
Error: Cannot find module 'timezone-list'

### ISSUE THREAD

**Issue by korifey91** [ndom91/react-timezone-select#51]
First of all thanks for this project.

When I was trying to add this package to my current project I have faced an issue.

Info about project
```
"next": "12.0.4",
"react-timezone-select": "^1.1.15",
```

I created a sandbox for you. Please take a look when you have time.
https://codesandbox.io/s/naughty-sound-v4dnl?file=/pages/index.js

**Comment by korifey91** [comment]
Adding this package to `next-transpile-modules` list fixes it for me

```ts
const withTM = require('next-transpile-modules')([
  'react-timezone-select',
]);
```

**Comment by ndom91** [comment]
Hi @korifey91, yes unfortunately this esm-only package still doesn't work 100% out of hte box with Next.js 12, although it was advertised with ESM support. I haven't had time to dig in and check whether its a problem on my side or what. This `next-transpile-modules` workaround is detailed in the readme here 😉

**Comment by ndom91** [comment]
Closing this as it seems resolved. If you have any further issues feel free to reopen or make a new issue :+1:

**Comment by devchris** [comment]
Same problem with react-scripts :(
