### ISSUE TITLE
Can we select back to empty string or null?

### ISSUE THREAD

**Issue by xmluozp** [ndom91/react-timezone-select#53]
In my case, it's an overriding time zone. I need it able to be set back to empty. (and show the placeholder)

**Comment by ndom91** [comment]
Hi @xmluozp yeah so the way I'd do this is to utilize the `react-select` prop `isClearable`. This will render an "X" at the end of the select dropdown to be able to clear, i.e. remove any selection.

So for example:
```js
<TimezoneSelect
  value={tz}
  onChange={setTz}
  isClearable
/>
```

See: https://react-select.com/props
