### ISSUE TITLE
Broken with latest react scripts v5?

### ISSUE THREAD

**Issue by devchris** [ndom91/react-timezone-select#54]
Since upgrading to react-scripts v5, the following error is produced:

```
Module not found: Error: Can't resolve './timezone-list' in '/frontend/node_modules/react-timezone-select/dist'
Did you mean 'timezone-list.js'?
BREAKING CHANGE: The request './timezone-list' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Is anyone else experiencing this issue as well?

**Comment by rislam169** [comment]
I am facing this error too

**Comment by sdevil7th** [comment]
I'm facing this too

**Comment by ndom91** [comment]
Hey thanks all for mentioning this, I will take a look :+1:

**Comment by dev11-dccolorweb** [comment]
Same here!

**Comment by christiansaavedra** [comment]
Im having it also

**Comment by DevinLeamy** [comment]
Same here

**Comment by DevinLeamy** [comment]
A temporary fix is to change `import allTimezones from './timezone-list` to `import allTimezones from './timezone-list.js';` in `dist/index.js` and `list/index.jsx`. Then you can build fresh with `npm run build`.

**Comment by tomi-bigpi** [comment]
> A temporary fix is to change `import allTimezones from './timezone-list` to `import allTimezones from './timezone-list.js';` in `dist/index.js` and `list/index.jsx`. Then you can build fresh with `npm run build`.

And you can save this change locally using https://www.npmjs.com/package/patch-package until this is resolved...

**Comment by ndom91** [comment]
Sorry yall, been swamped. I tried to replicate this in codesandbox with their CRA template (using `react-scripts@4.0.0` and `react-timezone-select@1.1.15`) and it seemed to work :shrug:.

Anyway, I implemented your temporary fix in `1.1.16`. Please let me know if that fixes the issue for you.

**Comment by alpritt** [comment]
Fixed it for me. Thank you.

**Comment by ndom91** [comment]
Hey yall, published a `1.2.0` where I published a correct esm + cjs version that worked just fine with `react-script@5.0.0+` in local testing

**Comment by ndom91** [comment]
Hey yall, unless there are any issues still open here I'm going to close this in the next days.

`v1.2.0` should hopefully fix this import / export issue :+1:

**Comment by tomi-bigpi** [comment]
@ndom91 Thanks for the update. CRA has been happy with 1.2.0. However, we just ran into an issue with Jest complaining with the following (abbreviated) error:
```
    /project-src-path/node_modules/react-timezone-select/dist/index.js:304
    import React3 from "react";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I'm still digging in to see if there's something we should do differently, but frankly we're just doing a regular `import TimezoneSelect from "react-timezone-select";`

Here's the full, slightly sanitized text, too:
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /project-src-path/node_modules/react-timezone-select/dist/index.js:304
    import React3 from "react";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      19 | import CustomComponent1 from "modules/common/components/CustomComponent1";
      20 | import CustomComponent2 from "modules/common/components/CustomComponent2";
    > 21 | import TimezoneSelect from "react-timezone-select";
         | ^
      22 | [snip ... other imports]

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/CustomPage.tsx:21:1)
```

**Comment by ndom91** [comment]
Yeah esbuild is bundling multiple copies of react in and I can't figure out how to avoid this correctly 🤔

**Comment by tomi-bigpi** [comment]
OK, I found the following workarounds:

* In `node_modules/react-timezone-select/package.json`, change `"main": "./dist/index.js",` to `"main": "./dist/index.cjs",`
* or, add the following to our project's `package.json`:
```
  "jest": {
    "moduleNameMapper": {
      "react-timezone-select": "<rootDir>/node_modules/react-timezone-select/dist/index.cjs"
    }
```

**Comment by ndom91** [comment]
Hey thanks for digging into this some more. 

The `main` value should have been pointing at the `index.cjs` version anyway. Just doing that worked for you? Unfortunately I still wasn't able to get it to work in Next.js with that change.

**Comment by tomi-bigpi** [comment]
Yes, pointing `main` to the `.cjs` version resolved the issue I was having with Jest tests.

**Comment by ndom91** [comment]
@tomi-bigpi just publish a `1.2.1` with this change :+1:

**Comment by talgki** [comment]
./src/components/shared/DynamicTimezone/index.js
Attempted import error: 'TimezoneSelect' is not exported from 'react-timezone-select'.

Hi, 
We are trying to make a new build, and now we are receiving this message. ): any ideas?

**Comment by ndom91** [comment]
Hey yeah my bad, having a hard time publishing this correctly with ESM / CJS so that it works with Next.js. CRA doesn't seem to be a problem. If anyone's got any insights there I'm all ears :joy:

For now, you can stick with `1.2.0`, for example.

**Comment by talgki** [comment]
> Hey yeah my bad, having a hard time publishing this correctly with ESM / CJS so that it works with Next.js. CRA doesn't seem to be a problem. If anyone's got any insights there I'm all ears :joy:
> 
> 
> 
> For now, you can stick with `1.2.0`, for example. 

Thanks for the reply! @ndom91 
We already tried downgrade to 1.2.0 but its still with the same errors. This errors accrues only from this morning and we didn't make any changes from our side (the site is in production).

**Comment by ndom91** [comment]
Okay I spent some more time with it, moved to rollup from esbuild, and _I think_ its working now.

I was able to get it imported into next.js 12 *without* the `next-transpile-modules* requirement as well.

**Comment by tomi-bigpi** [comment]
@ndom91 Our build, local development, and tests seem to run fine with version 1.3.0.

Thanks!

**Comment by ndom91** [comment]
Awesome, thanks for reporting back! ❤️

**Comment by ndom91** [comment]
Closing this as this issue has (finally) I believe been laid to rest! 

If anyone is still having issues, feel free to open a new one with your details.
