### ISSUE TITLE
Accept `date` prop for date-specific calculation of DST

### ISSUE THREAD

**Issue by james-camilleri** [ndom91/react-timezone-select#58]
With the current selector architecture, `isDST()` is always calculated on the current date. This leads to a scenario where the time zone names and offsets are incorrect if I'm trying to pick the time zone for a date other than today. For example, if I want to set a date of "3rd January 2020" and select Europe/Amsterdam as a time zone, but the current date is the 10th of June 2020, my time zone will show summer time and have an incorrect offset of +2hrs.

This can be trivially solved by passing an optional date, which would allow the DST check to be carried out the date required, as opposed to the current date. I've already got this working on a branch (I think), but if you're interested I'll look into writing some tests and getting it merged back into main.

**Comment by ndom91** [comment]
Sorry I'm only getting around to this now!

That seems like a legitimate use-case. If you've already got a branch open I'd be happy to take a look at a PR together. We can work out any last kinks together.

**Comment by james-camilleri** [comment]
So sorry, I'm totally swamped too! I do have a branch open, I think I've hammered out most of the edge cases, although it's best you have a look at how I've handled some of the stranger cases and see if it fits with your vision for the project. I also haven't written any tests yet, so I'll need to do that too.

**Comment by ndom91** [comment]
I'm going to close this issue, we can continue conversation in the PR. Thanks!
