### ISSUE TITLE
Can we prepend UTC instead of GMT?

### ISSUE THREAD

**Issue by ahmedbashir-dev** [ndom91/react-timezone-select#65]
Hi!
I am using this package which is working perfectly. Is there any prop to handle the prefix? I want to use UTC instead of GMT.

**Comment by ndom91** [comment]
So UTC is used only as a synonym (so to speak) for GMT+0:00, right. You want to use it instead of that? Or you want to replace all mentions of `GMT` with `UTC`, so that it'd be like `UTC+1:00`, `UTC+2:00`, etc. ?

**Comment by ahmedbashir-repo** [comment]
Hi, I understand that both are the same. I want to replace GMT with UTC as
text. Is it possible? I wasn't able to do so.

Thanks for your reply. Really appreciate it.

**Comment by ndom91** [comment]
Hi Ahmedbashir, as this isn't a standard, and in fact it goes against the standard very explicitly. I'm going to close this issue for now. If you really want it, I'd be happy to accept a PR to customize the `displayValue` entirely though.

**Comment by alex-airbox** [comment]
From what I've seen this never got traction? Not sure what standard are you following (I have no clue about time zones tbf), but I'm struggling to find any reference to GMT as a standard.

I was planning to use this but the first thing my team flagged was "it should say UTC, not GMT". 

From the W3C:

> What is a "zone offset"? A zone offset is the difference in hours and minutes between a particular time zone and UTC. In ISO 8601, the particular zone offset can be indicated in a date or time value. The zone offset can be Z for UTC or it can be a value "+" or "-" from UTC. For example, the value 08:00-08:00 represents 8:00 AM in a time zone 8 hours behind UTC, which is the equivalent of 16:00Z (8:00 plus eight hours). The value 08:00+08:00 represents the opposite increment, or midnight (08:00 minus eight hours).


And what I've read about the ISO_8601 it only talks about UTC.

**Comment by ndom91** [comment]
Yeah so UTC is definitely more often used nowadays when just referring to UTC (i.e. GMT+0:00). 

But timezone offsets are still almost always (as far as I've seen) migrated as `GMT+2:00`, for example.

**Comment by ndom91** [comment]
Ah but after doing some more research here, the `UTC+2:00` notation seems to be common as well. For example: https://www.time.gov/

If anyone wants to prepare a PR for a new displayValue option for this, I'd be happy to merge it

**Comment by alex-airbox** [comment]
I sent a PR from my other account some days ago, let me know if it looks ok.

**Comment by ndom91** [comment]
> I sent a PR from my other account some days ago, let me know if it looks ok.

Awesome, I just approved it. Looks great, thanks again! 

Will close this issue again (for real this time) now 🙏
