### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by jamesschwindt** [ndom91/react-timezone-select#68]
Hey I using Next 12.1 with react-timezone-select 1.3.1 .  Normally the timezone component works great but on older browsers such as Safari 12.1.2, Mobile Safari 13.0.4, and Samsung Internet 12.0, the component prevents the site from loading.  I'm aware I can use dynamic imports to catch errors before importing a module, but I wanted to mention this in case others have traffic from older browsers.
There's not a lot of info coming from the error:
```
Unhandled Runtime Error:
SyntaxError: Unexpected token '.'

Call Stack
eval
[native code]
./node_modules/react-timezone-select/dist/esm/index.js

```

**Comment by ndom91** [comment]
Hmm yeah that really isn't a lot to work with.. 

I'm thinking maybe it's an optional chainjng issue (`?.`) 

Is this a large portion of your users? Because generally we don't support anything but the last two versions of each browser, i.e. the browserslist default

**Comment by jamesschwindt** [comment]
About 10%, I've already replaced it with another time zone selector.  I just wanted to mention this in case others have problems.  Feel free to close the issue

**Comment by ndom91** [comment]
Okay thanks for the heads up, I'm going to close this for now. If anyone else comes across the issue, feel free to reopen!

**Comment by AmirJavaidSwe** [comment]
> About 10%, I've already replaced it with another time zone selector. I just wanted to mention this in case others have problems. Feel free to close the issue

Which other timezone selector you have used? I am facing this issue 
`react-timezone-select Identifier 'a' has already been declared`
