### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aelizabethian** [ndom91/react-timezone-select#69]
Hi, this isn't an issue but a question. I am trying to figure out how to style the react-timezone-select - specifically change the color of the background upon selection,  the border color on focus and the selected text. The blue doesn't fit my project but my normal styling that I would do isn't working (specifying hover states and specifying border color has no effect). Any advice?

**Comment by ndom91** [comment]
So without seeing a specific reproduction its hard for me to make a great suggestion.

However, I can tell you the underlying component that makes up the select element itself is [`react-select`](https://react-select.com). You can check out their docs on styling [here](https://react-select.com/styles).
