### ISSUE TITLE
Example components don't render on localhost

### ISSUE THREAD

**Issue by Toledodev** [ndom91/react-timezone-select#72]
Summary 
The "example" folder would supposedly render a component with the dropdown, but when ri run "npm dev" or "npm build" only a ".html" file is shown

Loom video: https://www.loom.com/share/07c76b8d7a82419ca317e216c316e62d

Obs.: Even if I enter the example folder and then run the project through it, the bug persists

**Comment by ndom91** [comment]
Hmm, the example folder, in the `main` branch of this repo, has a whole little mini project in it. I use it for development. 

If you clone the repo, cd into the `examples` dir, run `npm install`, and then `npm dev` - you should have the example project up and running.

**Comment by Toledodev** [comment]
yes, but when following these steps only the html component is show
![Screenshot from 2022-06-28 10-52-38](https://user-images.githubusercontent.com/87545086/176196332-5e499922-f282-4001-978b-a1859ecb2915.png)
n

**Comment by Toledodev** [comment]
Hey @ndom91, I recreated the folder
"examples", I believe you may have made some mistake regarding the use of vite, would you like the repository? It's exactly the same :+1:
