### ISSUE TITLE
Custom Styling CSS 

### ISSUE THREAD

**Issue by davidkmontes** [ndom91/react-timezone-select#80]
### Clear and concise description of the problem

I really appreciate this project but I'm not able to easily change the styling of the elements (with react). Especially for themes that have a light/dark style switch for users that prefer a dark version of a theme.

### Suggested solution

I think the best way would be to add props that define the name of the CSS class for the div elements. Thanks guys!

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
So the current implementation is basing the actual select dropdown component on `react-select`. They have a page about how to adjust styles available [here](https://react-select.com/styles).

However, there are some ideas brewing about dropping this dependency all together [here](https://github.com/ndom91/react-timezone-select/issues/64). However these are still in very early stages, so I wouldn't hold off to wait for this.

**Comment by davidkmontes** [comment]
Thank you! That helps a lot
