### ISSUE TITLE
Returning false value for Jordan(Asia/Amman)

### ISSUE THREAD

**Issue by Moshappp** [ndom91/react-timezone-select#83]
### Describe the bug

Jordan(Asia/Amman) timezone returns +2 Bucharest, while it should be +3
![Screen Shot 2023-01-09 at 12 12 19 AM](https://user-images.githubusercontent.com/117751089/211219400-87e2fe4b-345b-4b5a-8925-c8133e393e96.png)

It might be true that Jordan is +2 but taking into account DST as the library have mentioned it should be +3

![Screen Shot 2023-01-09 at 12 12 33 AM](https://user-images.githubusercontent.com/117751089/211219411-ed6241a1-feb6-410a-beaf-76b7c0be34fa.png)

### Reproduction

const [selectedTimezone, setSelectedTimezone] = useState("Asia/Amman");

### System Info

```Shell
+2 Bucharest
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Okay thanks for the heads up, I'm using the [`timezone-soft`](https://www.npmjs.com/package/timezone-soft) library for most of this. Is it the same there? Try this coesandbox: https://codesandbox.io/s/timezone-soft-test-jb1mq6?file=/src/App.js

**Comment by Moshappp** [comment]
@ndom91 True soft library returning +2 but if you expanded `daylight` object inside the console you would find `offset` is 3. I am not sure how you handle DST, but since you depend on soft library it might for some countries returns values taking into account DST while others not.

**Comment by ndom91** [comment]
We're determining whether to use the `dayliglht`/`standard` values based on `spacetime.now('Asia/Amman').isDST()` output from the [spacetime](https://npm.im/spacetime) library from the same maintainer as `timezone-soft`, so I assume they'd be using the same underlying data (like dates when DST happens), but maybe not.

Similar issue here btw: https://github.com/ndom91/react-timezone-select/issues/99

**Comment by ndom91** [comment]
I just updated the `timezone-soft` library to its latest version, can you confirm if this is still an issue? Bucharest is currently (middle of May) displaying as `GMT+3:00`:

![image](https://github.com/ndom91/react-timezone-select/assets/7415984/1b501ecb-6241-4a27-bb51-57ea2ae326bc)
