### ISSUE TITLE
react-select prop classNames not working due to outdated react-select version

### ISSUE THREAD

**Issue by Christopher-Stevers** [ndom91/react-timezone-select#84]
### Describe the bug

When attempt to pass a classNames prop to the TimezoneSelect component the expected styles changes within the component aren't occurring. Since I'm using tailwind it becomes a bit of an issue as I now need to write custom css for the select component.
I looked into the package a bit and looks like its due to the timezone-select package having an outdated version of react-select.

### Reproduction

https://github.com/Christopher-Stevers/react-timezone-repro/

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 1.28 GB / 15.93 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Thanks for the reproduction!

So that could definitely be.. This `react-timezone-select` is mainly a wrapper over `react-select` and I'm passing all additional props on to it. 

I just bumped `react-select` to `5.7.0` in the `1.4.0` release of [`react-timezone-select`](https://npm.im/react-timezone-select) though, can you give that a shot and let me know if it works for you?

**Comment by ndom91** [comment]
Closing for now, feel free to open a new issue if yuo're still having issues.
