### ISSUE TITLE
Timezone which doesn't return isDST from spacetime are not visible in timezone list

### ISSUE THREAD

**Issue by salmanorak** [ndom91/react-timezone-select#95]
### Describe the bug

When some time zones passed to the timezone-soft library, they don't return the "daylight" section in response objects. 

![image](https://user-images.githubusercontent.com/41747037/228811360-1980af96-20c8-425d-a2b8-aa7cb84329e8.png)

In some cases even if the timezone doesn't follow DST, spacetime is returning isDST as "true".

In the case of the "Asia/Tehran" timezone this issue happens.

The code in the below lines always expects to see daylight information in response
https://github.com/ndom91/react-timezone-select/blob/654f530b372d9ecfe9fb70a70624f6d1f605cced/src/index.tsx#L33

So when we hit this case the timezone is removed from the available list. 

### Reproduction

https://codesandbox.io/s/tehran-react-timezone-select-dhysvq?file=/src/App.js

### System Info

```Shell
spacetime: 7.4.1
timezone-soft: 1.4.1
```

### Extra Details
I have opened this issue to the library itself but it will be better to be safe from this kind of inconsistency.
https://github.com/spencermountain/spacetime/issues/379

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Yeah this makes sense, good catch! I just approved the PR as well. Will get it deployed asap

**Comment by ndom91** [comment]
Released in `v2.0.1`
