### ISSUE TITLE
GMT+00 Casablanca is in the wrong time zone

### ISSUE THREAD

**Issue by alex-airbox** [ndom91/react-timezone-select#99]
### Describe the bug

Casablanca appears as GMT+0, but currently it is in +1. I noticed that issue is probably with `timezone-soft` as they report it as UTC+00, but my browser renders any time set to `Africa/Casablanca` as UTC+01

Edit:
Actually `timezone-soft` seems correct, this is what it reports. Morocco is most of the year in standard (UTC+1), with the daylight used during Ramadan but that ended the 1st Sunday of May.

Is it just that `react-timezone-select` uses the `long` name provided by this `timezone-soft`?
```
{
    "name": "Morocco Standard Time",
    "iana": "Africa/Casablanca",
    "standard": {
        "abbr": "WET",
        "offset": 1,
        "name": "Morocco Standard Standard Time"
    },
    "daylight": {
        "abbr": "WEST",
        "offset": 0,
        "name": "Western European Summer Time",
        "start": "last-sun-mar-3h",
        "end": "1st-sun-may-2h"
    },
    "long": "(UTC+00:00) Casablanca"
}
```
---

![image](https://github.com/ndom91/react-timezone-select/assets/122016771/168525ff-ef71-4aca-a5f7-04ab159bd583)

### Reproduction

https://ndom91.github.io/react-timezone-select/

### System Info

```Shell
Your own demo, browsed on Chrome/windows (latest)
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Hmm yeah no so we stitch together the `standard.offset`, `standard.abbr`, or the `daylight` variant. Depending on whether `spacetime.now('Africa/Casablanca').isDST()` returns true or false.. :thinking:

**Comment by ndom91** [comment]
Same issue here btw: https://github.com/ndom91/react-timezone-select/issues/83

Where determining when DST is occuring / whether to use `daylight`/`standard` values is being incorrectly calculated :thinking:

**Comment by emrysal** [comment]
Hi @ndom91 - we just noticed the same thing; it looks like this is due to the underlying use of spacetime. See https://github.com/spencermountain/spacetime/issues/402

Spacetime isn't DST aware.

**Comment by ndom91** [comment]
I just updated the `timezone-soft` library to its latest version, can you confirm if this is still an issue? Currently (middle of May) Casablanca is showing as `GMT+1:00`:

![image](https://github.com/ndom91/react-timezone-select/assets/7415984/9d67d430-ccba-4ab8-8c62-ea3a24bcbcc4)

Demo: https://ndom91.github.io/react-timezone-select/
